version: '3.7'

services:
  app:
    volumes:
      - ./app:/app
    command: flask run --host=0.0.0.0
    environment:
      - FLASK_ENV=development
      - MEDIA_ROOT=/app/media/
    ports:
      - 5000:5000
