version: '3.7'

services:
  app:
    build: app
    restart: always
    environment:
      - VIRTUAL_HOST=194.67.116.20
  nginx-proxy:
    restart: always
    build: nginx-proxy
    ports:
      - 80:80
    volumes:
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-dhparam:/etc/nginx/dhparam
      - nginx-html:/usr/share/nginx/html
      - nginx-vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  nginx-certs:
  nginx-dhparam:
  nginx-html:
  nginx-vhost:
